name: Deploy Backend Server to Production Render

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug list server files
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          ls -la server || true
          git ls-files server/package.json || echo "package.json not tracked"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'  # Align with your local version

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: |
          cd server
          pnpm install

      - name: Run tests
        run: |
          cd server
          pnpm test || true

      - name: Deploy To Render
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST https://api.render.com/v1/services/srv-${RENDER_SERVICE_ID}/deploys \
          -H "Authorization: Bearer ${RENDER_API_KEY}" \
          -H "Content-Type: application/json"

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Backend server deployed successfully to Render."
          else
            echo "❌ Backend server deployment failed. Check the logs."
          fi
